keep_files: ['css', 'js']
include: ['_pages']
relative_permalinks: false
timezone: America/New_York
encoding: utf-8
product: Docker
keywords: juju, juju charms, docker
analytics_id: UA-XXX
repository: chuckbutler/docker-charm
forkme_enabled: true
url: http://chuckbutler.github.io/docker-charm
