options:
  latest:
    type: boolean
    default: False
    description: |
      If True, deploy the latest version of docker, when False (default)
      installs docker.io from the Ubuntu package archive."
  version:
    type: string
    default: 1.8.1-0~trusty
    description: |
      When latest = true, specify the version to install from the PPA.
      latest = false will always assume use the current stable in distro.
  compose:
    type: boolean
    default: true
    description: |
        Install docker compose, the formation launch utility
  aufs:
    type: boolean
    default: true
    description: |
        Change the backend storage driver from devicemapper to AUFS.
        The device mapper storage engine is known to be problematic, and AUFS
        is not enabled by default in Ubuntu. This will install AUFS support and
        swap the backend. **NOTE** It is not recommended to reconfigure this post
        deployment. You may incur dataloss.
