options:
  latest:
    type: boolean
    default: False
    description: | 
      If True, deploy the latest version of docker, when False (default) 
      installs docker.io from the Ubuntu package archive."
  version:
    type: string
    default: 1.5.0
    description: |
      When latest = true, specify the version to install from the PPA.
      latest = false will always assume use the current stable in distro.
  iperf-docker:
      type: boolean
      default: True
      description: |
        If True, will deploy the iperf network benchmarking daemon in a docker
        container, typically to benchmark the SDN configuration applied to
        the docker host.
