options:
  latest:
    type: boolean
    default: False
    description: |
      If True, deploy the latest version of docker, when False (default)
      installs docker.io from the Ubuntu package archive."
  version:
    type: string
    default: 1.7.0
    description: |
      When latest = true, specify the version to install from the PPA.
      latest = false will always assume use the current stable in distro.
  compose:
    type: boolean
    default: true
    description: |
        Install docker compose, the formation launch utility

