---
# Primary concern is handling data being sent over the wire from subordinate services
# such as the flannel-docker charm.

# Read and scrub data for use
- name: Check Installation Status
  include: installation-status.yaml

- name: Receive Relationship Data subnet
  shell: relation-get flannel-subnet
  register: flannel_subnet

- name: Receive Relationship Data mtu
  shell: relation-get flannel-mtu
  register: flannel_mtu

- set_fact:
    flannel_mtu: "{{ flannel_mtu.stdout }}"
    flannel_subnet: "{{ flannel_subnet.stdout }}"

- name: Cache network subnet
  shell: echo "{{ flannel_subnet }} >> .flannel_subnet"
  args:
    chdir: "{{ charm_dir }}"
    creates: .flannel-subnet

- name: Cache network mtu
  shell: echo "{{ flannel_mtu }} >> .flannel-mtu"
  args:
    chdir: "{{ charm_dir }}"
    creates: .flannel-mtu


