- hosts: all
  tasks:

      - name: Check Installation Status
      include: installation-status.yaml

      - name: install or upgrade
      include: install-or-upgrade.yaml
      tags:
        - install
        - upgrade-charm

    - name: config changed
      include: config-changed.yaml
      tags:
        - config-changed

    - name: Docker Network Relation Changed
      include: subordinate-actions.yaml
      tags:
        - network-relation-changed

