- hosts: all
  vars:
    opts_yaml: /etc/ansible/docker-opts.yaml
    docker_version_name: false
  handlers:
    - name: restart docker
      service: "name={{docker_version_name}} state=restarted"
    - name: calculate docker opts
      docker_opts: "action=read yaml={{opts_yaml}}"
    - name: render docker defaults
      template: "src=templates/docker-defaults dest=/etc/default/{{docker_version_name}}"
  tasks:
    - name: Check Installation Status
      include: installation-status.yaml
      tags:
        - network-relation-changed
        - stop

    - name: install or upgrade
      include: install-or-upgrade.yaml
      tags:
        - install
        - upgrade-charm

    - name: config changed
      include: config-changed.yaml
      tags:
        - config-changed

    - name: Docker Network Relation Changed
      include: network-relation-changed.yaml
      tags:
        - network-relation-changed

    - name: Uninstall Docker
      include: uninstall-docker.yaml
      tags:
        - stop

    - name: Set Status to ready
      shell: "status-set active ''"
      tags:
        - config-changed
        - start

