---
# Cache the fact data for later config updates outside of the relationship context
# If we modify docker defaults later, the data is lost without it being cached.

- name: Check Installation Status
  include: installation-status.yaml

- name: Ingest Relation Data
  include: ingest-relation-data.yaml

# Call the data from cache for usage in the representative templates, always

#- name: Read flannel Data
#  register: 

- set_fact:
    docker_opts: "--bip {{ flannel-subnet }}"
    when: "{{ flannel-subnet != '' }}"

- set_fact:
    docker_opts: "{{ docker_opts }} --mtu {{ flannel-mtu }}"
    when: "{{ flannel-mtu != '' }}"

- name: Render docker defaults template
  template: src=templates/docker dest=/etc/defaults/docker


