---
# Cache the fact data for later config updates outside of the relationship context
# If we modify docker defaults later, the data is lost without it being cached.

- name: Check Installation Status
  include: installation-status.yaml

- name: Ingest Relation Data
  include: ingest-relation-data.yaml


- set_fact:
    docker_opts: "--bip {{ flannel_subnet }}"
    when: "{{ flannel_subnet != '' }}"

- set_fact:
    docker_opts: "{{ docker_opts }} --mtu {{ flannel_mtu }}"
    when: "{{ flannel_mtu != '' }}"

- name: Render docker defaults template
  template: src=docker dest=/etc/default/docker.io
  when: universe_installed

- name: Render docker defaults template
  template: src=docker dest=/etc/default/docker
  when: latest_installed

- name: Halt docker service
  service: name=docker state=stopped
  when: latest_installed

- name: Halt docker service
  service: name=docker.io state=stopped
  when: universe_installed

- name: Bring Docker Bridge offline
  shell: ifconfig docker0 down

- name: Delete Docker Bridge
  shell: brctl delbr docker0

- name: Restart Docker
  service: name=docker state=restarted
  when: latest_installed

- name: Restart Docker
  service: name=docker.io state=restarted
  when: universe_installed

